Deshboard/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views,SupreUserViews,OrganizationUserViews,GovernmentUserViews

urlpatterns = [

    path('',views.userlogin,name='login'),
    path('logout',views.userlogout,name='logout'),
    path('password_change', views.ChangePassword,name="password_change"),

    # supreUserViews
    path('suprofile/',SupreUserViews.profile,name="suprofile"),
    path('superuser/',SupreUserViews.home, name='SuHome'),
    path('createGovUser/',SupreUserViews.CreateGovUser, name='createGovUser'),
    path('createOrUser/',SupreUserViews.CreateOrUser, name='CreateOrUser'),
    path('createForm/',SupreUserViews.CreateFormfun, name='CreateForm'),
    path('showformList/',SupreUserViews.ShowformList, name='ShowformList'),
    path('showForm/<slug:pid>',SupreUserViews.formshow, name='ShowForm'),
    path('createProject',SupreUserViews.CreateProjectFun, name='CreateProject'),
    path('showProject',SupreUserViews.ShowProject, name='ShowProject'),
    path('showProjectDetail/<slug:pid>',SupreUserViews.ShowProjectDetail, name='ShowProjectDetail'),
    path('editProjectDetail/<slug:pid>',SupreUserViews.editProjectDetail, name='editProjectDetail'),
    path('deleteProject/<slug:pid>',SupreUserViews.deleteProject, name='deleteProject'),
    path('appliedProjectList',SupreUserViews.showAllProjects, name='appliedProjectList'),
    path('appliedProjectDetail/<slug:pid>',SupreUserViews.appliedProjectDetail, name='appliedProjectDetail'),
    path('assignProject/<slug:pid>',SupreUserViews.assignProject, name='assignProject'),
    path('trackProject/',SupreUserViews.trackProjectfun, name='trackProject'),
    path('trackProject/<slug:pid>',SupreUserViews.trackProjectadd, name='trackProjectadd'),
    path('completeProject/',SupreUserViews.completeProject, name='completeProject'),
    path('completeProjectAdd/<slug:pid>',SupreUserViews.completeProjectAdd, name='completeProjectAdd'),
    path('manageGovUser/',SupreUserViews.manageGovUser, name='manageGovUser'),
    path('manageOrUser/',SupreUserViews.manageOrUser, name='manageOrUser'),
    path('deleteUser/<slug:uid>',SupreUserViews.deleteUser, name='deleteUser'),
    path('GovProfileShow/<slug:uid>',SupreUserViews.GovProfileShow, name='GovProfileShow'),
    path('OrganizationProfileShow/<slug:uid>',SupreUserViews.OrganizationProfileShow, name='OrganizationProfileShow'),

    # GovernmentUserViews
    path('goprofile/',GovernmentUserViews.profile,name="goprofile"),
    path('government/',GovernmentUserViews.home, name='GoHome'),


    # OrganizationUserViews
    path('orprofile/',OrganizationUserViews.profile,name="orprofile"),
    path('addPastProjects/',OrganizationUserViews.addPastProjects,name="addPastProjects"),
    path('organization/',OrganizationUserViews.home, name='OrHome'),
    path('showProjectOr',OrganizationUserViews.ShowProject, name='showProjectOr'),
    path('applyProjectDetail/<slug:pid>',OrganizationUserViews.applyProjectDetail, name='applyProjectDetail'),
    path('fillprojectform/<slug:pid>/<str:name>',OrganizationUserViews.fillprojectform, name='fillprojectform'),
    path('applyFinalProject/<slug:pid>',OrganizationUserViews.apply_Project_post, name='apply_Project_post'),
    path('showAppliedProject/',OrganizationUserViews.showAppliedProject, name='showAppliedProject'),
    path('applyshowForm/<slug:pid>',OrganizationUserViews.formshow, name='applyShowForm'),
    path('showCurrentProject/',OrganizationUserViews.showCurrentProject, name='showCurrentProject'),
    path('trackProjectShow/<slug:pid>',OrganizationUserViews.trackProjectShow, name='trackProjectShow'),
    path('completeProjector/',OrganizationUserViews.completeProject, name='completeProjector'),
    path('completeProjectShow/<slug:pid>',OrganizationUserViews.completeProjectShow, name='completeProjectShow'),




    # reset_password

    path('reset_password/',
    auth_views.PasswordResetView.as_view(template_name="Deshboard/password_reset.html"),
    name="reset_password"),

    path('reset_password_sent/',
    auth_views.PasswordResetDoneView.as_view(template_name="Deshboard/password_reset_sent.html"),
    name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(template_name="Deshboard/password_reset_form.html"),
    name="password_reset_confirm"),

    path('reset_password_complete/',
    auth_views.PasswordResetCompleteView.as_view(template_name="Deshboard/password_reset_done.html"),
    name="password_reset_complete"),


]

PaperLessOffice/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Deshboard.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



Deshboard/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone

# Create your models here.

class CustomUser(AbstractUser):
    user_type_data=((1,"SuperUser"),(2,"GovernmentUser"),(3,"OrganizationUser"))
    user_type=models.CharField(default=1,choices=user_type_data,max_length=20)

class SuperUserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    phone = PhoneNumberField(null=True)
    Position = models.CharField(max_length=200, null=True,blank=True)
    education = models.CharField(max_length=255, null=True,blank=True)
    location = models.CharField(max_length=255, null=True,blank=True)
    experiance = models.TextField(null=True,blank=True)
    profile_pic = models.ImageField(default="profile1.png", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.user.username
        

class GovermentUserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    goverment_id=models.IntegerField(unique=True,null=True)
    job_role=models.CharField(max_length=200, null=True)
    phone = PhoneNumberField()
    education = models.CharField(max_length=255, null=True,blank=True)
    location = models.CharField(max_length=255, null=True,blank=True)
    experiance = models.TextField(null=True,blank=True)
    profile_pic = models.ImageField(default="profile1.png", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)


    def __str__(self):
        return self.user.username

class OrganizationUserProfile(models.Model):
    user = models.OneToOneField(CustomUser,null=True, on_delete=models.CASCADE)
    organization_id=models.IntegerField(unique=True,null=True)
    organization_name=models.CharField(max_length=200, null=True)
    phone = PhoneNumberField()
    total_project = models.IntegerField(null=True,default=0,blank=True)
    location = models.CharField(max_length=255, null=True,blank=True)
    experiance = models.TextField(null=True,blank=True)
    profile_pic = models.ImageField(default="profile1.png", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)


    def __str__(self):
        return self.user.username

class CreateForm(models.Model):
    form_name = models.CharField(max_length=255,unique=True)
    form_code = models.TextField()
    created_at= models.DateTimeField(auto_now_add=True, null=True)
    updated_at= models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.form_name

class CreateProject(models.Model):
    project_name = models.CharField(max_length=255, unique=True)
    project_description = models.TextField()
    status_choices = [('pending','pending'),('assigned','assigned'),('completed','completed')] 
    status = models.CharField(max_length=15,choices=status_choices,default='pending')
    forms = models.ManyToManyField(CreateForm)
    estimated_budget = models.CharField(max_length=30,null=True)
    estimated_project_duration = models.CharField(max_length=15,null=True)
    apply_start_date = models.DateTimeField(null=True)
    apply_end_date = models.DateTimeField(null=True)
    assigned_by = models.CharField(max_length=255,null=True)
    assigned_to = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True)
    assigned_details = models.TextField(null=True)
    project_progress = models.IntegerField(null=True,default=0,blank=True)
    Complete_details = models.TextField(null=True)
    complete_Rating = models.DecimalField(max_digits=2, decimal_places=1,null=True)
    created_at= models.DateTimeField(auto_now_add=True, null=True)
    updated_at= models.DateTimeField(auto_now_add=True, null=True)

    @property
    def is_On_Time(self):
        return (timezone.now() > self.apply_start_date) and (timezone.now() < self.apply_end_date)

    def __str__(self):
        return self.project_name


class FormData(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    project = models.ForeignKey(CreateProject, on_delete=models.CASCADE)
    form_name= models.ForeignKey(CreateForm,on_delete=models.PROTECT)
    submited_data = models.JSONField(null=True, blank=True)
    submited_File = models.JSONField(null=True, blank=True)
    submited_at= models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        constraints = [models.UniqueConstraint(fields=['user','project','form_name'],name='user_project_formName')]

    def __str__(self):
        return str(self.user)+" "+str(self.project)+" "+str(self.form_name)

class applyProject(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    project = models.ForeignKey(CreateProject, on_delete=models.CASCADE)
    forms = models.ManyToManyField(FormData)
    date_applyed = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        constraints = [models.UniqueConstraint(fields=['user','project'],name='user_project_forms')]

    def __str__(self):
        return str(self.user)+" "+str(self.project)

class trackProject(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    project = models.ForeignKey(CreateProject, on_delete=models.CASCADE)
    track_status=models.CharField(max_length=255,null=True)
    track_description = models.TextField()
    project_progress = models.IntegerField(null=True,default=0,blank=True)
    created_at= models.DateTimeField(auto_now_add=True, null=True)
    updated_at= models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.track_status)+" "+str(self.project)+" "+str(self.user)


class pastProject(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    project_name = models.CharField(max_length=255)
    project_description = models.TextField()
    estimated_budget = models.CharField(max_length=30,null=True)
    estimated_project_duration = models.CharField(max_length=15,null=True)
    Complete_details = models.TextField(null=True)
    complete_Rating = models.DecimalField(max_digits=2, decimal_places=1,null=True)
    created_at= models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str(self.user) +" "+ str(self.project_name)

@receiver(post_save,sender=CustomUser)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        if instance.user_type==1:
            SuperUserProfile.objects.create(user=instance)
        if instance.user_type==2:
            GovermentUserProfile.objects.create(user=instance)
        if instance.user_type==3:
            OrganizationUserProfile.objects.create(user=instance)

@receiver(post_save,sender=CustomUser)
def save_user_profile(sender,instance,**kwargs):
    if instance.user_type==1:
        instance.superuserprofile.save()
    if instance.user_type==2:
        instance.govermentuserprofile.save()
    if instance.user_type==3:
        instance.organizationuserprofile.save()


@receiver(post_save,sender=pastProject)
def Update_user_profile_project(sender,instance,created,**kwargs):
    if created:
        print(instance)
        print(instance.user)
        profile = OrganizationUserProfile.objects.filter(user=instance.user).first()
        past_project_count = pastProject.objects.filter(user=instance.user).count()
        profile.total_project = past_project_count
        profile.save()
        print("project updated")

Deshboard/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import SuperUserProfile,GovermentUserProfile,OrganizationUserProfile,CustomUser,CreateProject,pastProject

User = get_user_model()

class CreateUserForm(UserCreationForm):

	class Meta:
		model = User
		fields  =['username', 'email', 'password1', 'password2','first_name','last_name']

class UpdateUserForm(ModelForm):

	class Meta:
		model = User
		fields  =['username', 'email','first_name','last_name']
	

class SuperUserProfileForm(ModelForm):
	class Meta:
		model = SuperUserProfile
		fields = '__all__'
		exclude =['user']


class GovermentUserProfileForm(ModelForm):
	class Meta:
		model = GovermentUserProfile
		fields = '__all__'
		exclude =['user']


class OrganizationUserProfileForm(ModelForm):
	class Meta:
		model = OrganizationUserProfile
		fields = '__all__'
		exclude =['user','total_project']

class CreateProjectForm(ModelForm):
	class Meta:
		model = CreateProject
		fields = '__all__'
		exclude =['assigned_by','assigned_to','assigned_details','Complete_details','complete_Rating']

class AddPastProjectsForm(ModelForm):
	class Meta:
		model = pastProject
		fields = '__all__'
		exclude=['user','Complete_details','complete_Rating']

Deshboard/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm


# Create your views here.

def userlogin(request):
    if request.user.is_authenticated:
        if request.user.user_type == '1':
            print(request.user.id)
            return redirect('SuHome')
        elif request.user.user_type == '2':
            return redirect('GoHome')
        elif request.user.user_type == '3':
            return redirect('OrHome')
    else:
        if request.method == 'POST':
            username =request.POST.get('username')
            password =request.POST.get('password')
            user = authenticate(request,username=username,password=password)

            if user is not None:
                login(request,user)
                if user.user_type == '1':
                    return redirect("SuHome")
                elif user.user_type == '2':
                    return redirect("GoHome")
                elif user.user_type == '3':
                    return redirect("OrHome")
            else:
                messages.info(request, 'Username OR Password is incorrect.')
        
    contex={}
    return render(request, 'Deshboard/login.html',contex)

@login_required(login_url='login')
def userlogout(request):
	logout(request)
	return redirect('login')

@login_required(login_url='login')
def ChangePassword(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
        user=''
    if request.user.user_type == '1':
        user='Deshboard/Superuser/superuser.html'
    elif request.user.user_type == '2':
        user='Deshboard/Governmentuser/government.html'
    elif request.user.user_type == '3':
        user='Deshboard/Organizationuser/organization.html'
    contex = {'form':form,"user":user}
    return render(request, 'Deshboard/change_password.html',contex)

Deshboard/templates/Deshboard/Governmentuser/goprofile.html
{% extends './government.html' %}

{% block tabTitle %}
Profile
{% endblock %}


{% block bodyContent %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
  <strong>Message :</strong>{{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% include '../profile.html' %}

{% endblock %}

Deshboard/templates/Deshboard/Governmentuser/government.html
{% extends "../basic.html" %}

{% block title %}
<title>Goverment User | Dashboard</title>
{% endblock  %}

{% block userhome %}
{% url 'GoHome' %}
{% endblock %}

{% block profile_url %}
{% url 'goprofile' %}
{% endblock profile_url %}


{% block profile_pic %}
{{request.user.govermentuserprofile.profile_pic.url}}
{% endblock %}

{% block loginname %}
{{request.user.username}}
{% endblock %}

{% block sidebar %}

<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

        <!-- home nav -->
        <li class="nav-item">
          <a href="{% url 'GoHome' %}" class="nav-link {% block HomeActive %}{% endblock %}">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              Home
            </p>
          </a>
        </li>

        <!-- Projects -->
        <li class="nav-item {% block projectopen %}{% endblock projectopen %}">
          <a href="#" class="nav-link {% block projectactive %}{% endblock projectactive %}">
            <i class="nav-icon fas fa-edit"></i>
            <p>
              Project
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'ShowProject' %}" class="nav-link {% block ShowProjectActive %}{% endblock ShowProjectActive %}">
                <i class="far fa-circle nav-icon"></i>
                <p>Show Project</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'ShowformList' %}" class="nav-link {% block ShowFormActive %}{% endblock ShowFormActive %}">
                <i class="far fa-circle nav-icon"></i>
                <p>Show Form</p>
              </a>
            </li>
          </ul>
        </li>

        <!-- applied projects -->
        <li class="nav-item {% block appliedprojectopen %}{% endblock appliedprojectopen %}">
          <a href="#" class="nav-link {% block appliedprojectactive %}{% endblock appliedprojectactive %}">
            <i class="nav-icon fas fa-tasks"></i>
            <p>
              Applied Project
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'appliedProjectList' %}" class="nav-link {% block ApplideProjectListActive %}{% endblock %}">
                <i class="far fa-circle nav-icon"></i>
                <p>Applied Project Show</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'trackProject' %}" class="nav-link {% block TrackProjectActive %}{% endblock %}">
                <i class="far fa-circle nav-icon"></i>
                <p>Track Project</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'completeProject' %}" class="nav-link {% block complateProjectActive %}{% endblock complateProjectActive %}">
                <i class="far fa-circle nav-icon"></i>
                <p>Complete Project</p>
              </a>
            </li>
          </ul>
        </li>

        <!-- Show Organization -->
        <li class="nav-item">
          <a href="{% url 'manageOrUser' %}" class="nav-link {% block ManageOrUserActive %}{% endblock ManageOrUserActive %}">
            <i class="far fa-user nav-icon"></i>
            <p>Show Organization</p>
          </a>
        </li>


  </ul>

{% endblock %}

{% block ContentHeader %}

<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Dashboard</h1>
        </div><!-- /.col -->
        
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>


{% endblock %}


Deshboard/templates/Deshboard/Governmentuser/profile.html
{% extends './government.html' %}


{% block body %}

<div class="container-fluid">

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3">

            <!-- Profile Image -->
            <div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle"
                       src="{{request.user.govermentuserprofile.profile_pic.url}}"
                       alt="User profile picture">
                </div>

                <h3 class="profile-username text-center">{{request.user.get_username}}</h3>

                <p class="text-muted text-center">{{request.user.govermentuserprofile.job_role}}</p>

                <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item">
                    <b>Name :</b> <a class="float-right">{{request.user.get_full_name}}</a>
                  </li>
                  <li class="list-group-item">
                    <b>Email :</b> <a  href="mailto:{{request.user.email}}" target="_blank" class="float-right">{{request.user.email}}</a>
                  </li>
                  <li class="list-group-item">
                    <b>Date Join :</b> <a class="float-right">{{request.user.date_joined}}</a>
                  </li>
                </ul>

                
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- About Me Box -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">About Me</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <strong><i class="fas fa-book mr-1"></i> Education</strong>

                <p class="text-muted">
                  {{request.user.govermentuserprofile.education}}
                </p>

                <hr>

                <strong><i class="fas fa-map-marker-alt mr-1"></i> Location</strong>

                <p class="text-muted">{{request.user.govermentuserprofile.location}}</p>

                <hr>

                <strong><i class="fas fa-pencil-alt mr-1"></i>Phone Number</strong>

                <p class="text-muted">
                  {{request.user.govermentuserprofile.phone}}
                </p>

                
                <strong><i class="far fa-file-alt mr-1"></i> Experience</strong>

                <p class="text-muted">{{request.user.govermentuserprofile.experiance}}</p>

              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
          <div class="col-md-9">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#settings" data-toggle="tab">Settings</a></li>
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">
                  
                  <!-- /.tab-pane -->
                  <div class="active tab-pane" id="settings">
                    {% include "../message.html" %}
                    <form class="form-horizontal" method="POST" enctype="multipart/form-data">{% csrf_token %}
                      <div class="form-group row">
                        <label for="id_first_name" class="col-sm-2 col-form-label">First Name</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control" name="first_name" id="id_first_name" value="{{form.first_name.value}}" placeholder="First Name" required>
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="id_last_name" class="col-sm-2 col-form-label">Last Name</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control" name="last_name" id="id_last_name" value="{{form.last_name.value}}" placeholder="Last Name" required>
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="id_username" class="col-sm-2 col-form-label">User Name</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control" name="username" id="id_username" value="{{form.username.value}}" placeholder="User Name" autofocus required>
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="id_goverment_id" class="col-sm-2 col-form-label">Goverment id</label>
                        <div class="col-sm-10">
                          <input type="number" class="form-control" name="goverment_id" id="id_goverment_id" value="{{profileForm.goverment_id.value}}" placeholder="Goverment id" required="">
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="id_job_role" class="col-sm-2 col-form-label">Job role</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control" name="job_role" id="id_job_role" value="{{profileForm.job_role.value}}" maxlength="200" placeholder="Job role" required="">
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="id_education" class="col-sm-2 col-form-label">Education</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control" name="education" id="id_education" value="{{profileForm.education.value}}" placeholder="Education">
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="id_location" class="col-sm-2 col-form-label">Location</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control" name="location" id="id_location" value="{{profileForm.location.value}}" placeholder="Location">
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="id_email" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                          <input type="email" class="form-control" name="email" id="id_email" value="{{form.email.value}}" placeholder="Email" required >
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="id_phone" class="col-sm-2 col-form-label">Contact number</label>
                        <div class="col-sm-10">
                          <input type="tel" id="id_phone" maxlength="128" name="phone" class="form-control" value="{{profileForm.phone.value}}" placeholder="Contact Number" required>
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="id_experiance" class="col-sm-2 col-form-label">Experience</label>
                        <div class="col-sm-10">
                          <textarea class="form-control" name="experiance" id="id_experiance" placeholder="Experience">{{profileForm.experiance.value}}</textarea>
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="id_profile_pic" class="col-sm-2 col-form-label">Profile pic:</label>
                        <div class="col-sm-10">
                          {{profileForm.profile_pic}}
                        </div>
                      </div>
                      <div class="form-group row">
                        <div class="offset-sm-2 col-sm-10">
                          <button type="submit" class="btn btn-danger">Submit</button>
                        </div>
                      </div>
                      <!-- {{profileForm}} -->
                      {% include "../error.html" %}
                    </form>
                  </div>
                  <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

</div>

{% endblock %}