Deshboard/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views,SupreUserViews,OrganizationUserViews,GovernmentUserViews

urlpatterns = [

    path('',views.userlogin,name='login'),
    path('logout',views.userlogout,name='logout'),
    path('password_change', views.ChangePassword,name="password_change"),

    # supreUserViews
    path('suprofile/',SupreUserViews.profile,name="suprofile"),
    path('superuser/',SupreUserViews.home, name='SuHome'),
    path('createGovUser/',SupreUserViews.CreateGovUser, name='createGovUser'),
    path('createOrUser/',SupreUserViews.CreateOrUser, name='CreateOrUser'),
    path('createForm/',SupreUserViews.CreateFormfun, name='CreateForm'),
    path('showformList/',SupreUserViews.ShowformList, name='ShowformList'),
    path('showForm/<slug:pid>',SupreUserViews.formshow, name='ShowForm'),
    path('createProject',SupreUserViews.CreateProjectFun, name='CreateProject'),
    path('showProject',SupreUserViews.ShowProject, name='ShowProject'),
    path('showProjectDetail/<slug:pid>',SupreUserViews.ShowProjectDetail, name='ShowProjectDetail'),
    path('editProjectDetail/<slug:pid>',SupreUserViews.editProjectDetail, name='editProjectDetail'),
    path('deleteProject/<slug:pid>',SupreUserViews.deleteProject, name='deleteProject'),
    path('appliedProjectList',SupreUserViews.showAllProjects, name='appliedProjectList'),
    path('appliedProjectDetail/<slug:pid>',SupreUserViews.appliedProjectDetail, name='appliedProjectDetail'),
    path('assignProject/<slug:pid>',SupreUserViews.assignProject, name='assignProject'),
    path('trackProject/',SupreUserViews.trackProjectfun, name='trackProject'),
    path('trackProject/<slug:pid>',SupreUserViews.trackProjectadd, name='trackProjectadd'),
    path('completeProject/',SupreUserViews.completeProject, name='completeProject'),
    path('completeProjectAdd/<slug:pid>',SupreUserViews.completeProjectAdd, name='completeProjectAdd'),
    path('manageGovUser/',SupreUserViews.manageGovUser, name='manageGovUser'),
    path('manageOrUser/',SupreUserViews.manageOrUser, name='manageOrUser'),
    path('deleteUser/<slug:uid>',SupreUserViews.deleteUser, name='deleteUser'),
    path('GovProfileShow/<slug:uid>',SupreUserViews.GovProfileShow, name='GovProfileShow'),
    path('OrganizationProfileShow/<slug:uid>',SupreUserViews.OrganizationProfileShow, name='OrganizationProfileShow'),

    # GovernmentUserViews
    path('goprofile/',GovernmentUserViews.profile,name="goprofile"),
    path('government/',GovernmentUserViews.home, name='GoHome'),


    # OrganizationUserViews
    path('orprofile/',OrganizationUserViews.profile,name="orprofile"),
    path('addPastProjects/',OrganizationUserViews.addPastProjects,name="addPastProjects"),
    path('organization/',OrganizationUserViews.home, name='OrHome'),
    path('showProjectOr',OrganizationUserViews.ShowProject, name='showProjectOr'),
    path('applyProjectDetail/<slug:pid>',OrganizationUserViews.applyProjectDetail, name='applyProjectDetail'),
    path('fillprojectform/<slug:pid>/<str:name>',OrganizationUserViews.fillprojectform, name='fillprojectform'),
    path('applyFinalProject/<slug:pid>',OrganizationUserViews.apply_Project_post, name='apply_Project_post'),
    path('showAppliedProject/',OrganizationUserViews.showAppliedProject, name='showAppliedProject'),
    path('applyshowForm/<slug:pid>',OrganizationUserViews.formshow, name='applyShowForm'),
    path('showCurrentProject/',OrganizationUserViews.showCurrentProject, name='showCurrentProject'),
    path('trackProjectShow/<slug:pid>',OrganizationUserViews.trackProjectShow, name='trackProjectShow'),
    path('completeProjector/',OrganizationUserViews.completeProject, name='completeProjector'),
    path('completeProjectShow/<slug:pid>',OrganizationUserViews.completeProjectShow, name='completeProjectShow'),




    # reset_password

    path('reset_password/',
    auth_views.PasswordResetView.as_view(template_name="Deshboard/password_reset.html"),
    name="reset_password"),

    path('reset_password_sent/',
    auth_views.PasswordResetDoneView.as_view(template_name="Deshboard/password_reset_sent.html"),
    name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(template_name="Deshboard/password_reset_form.html"),
    name="password_reset_confirm"),

    path('reset_password_complete/',
    auth_views.PasswordResetCompleteView.as_view(template_name="Deshboard/password_reset_done.html"),
    name="password_reset_complete"),


]

PaperLessOffice/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Deshboard.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



Deshboard/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone

# Create your models here.

class CustomUser(AbstractUser):
    user_type_data=((1,"SuperUser"),(2,"GovernmentUser"),(3,"OrganizationUser"))
    user_type=models.CharField(default=1,choices=user_type_data,max_length=20)

class SuperUserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    phone = PhoneNumberField(null=True)
    Position = models.CharField(max_length=200, null=True,blank=True)
    education = models.CharField(max_length=255, null=True,blank=True)
    location = models.CharField(max_length=255, null=True,blank=True)
    experiance = models.TextField(null=True,blank=True)
    profile_pic = models.ImageField(default="profile1.png", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.user.username
        

class GovermentUserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    goverment_id=models.IntegerField(unique=True,null=True)
    job_role=models.CharField(max_length=200, null=True)
    phone = PhoneNumberField()
    education = models.CharField(max_length=255, null=True,blank=True)
    location = models.CharField(max_length=255, null=True,blank=True)
    experiance = models.TextField(null=True,blank=True)
    profile_pic = models.ImageField(default="profile1.png", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)


    def __str__(self):
        return self.user.username

class OrganizationUserProfile(models.Model):
    user = models.OneToOneField(CustomUser,null=True, on_delete=models.CASCADE)
    organization_id=models.IntegerField(unique=True,null=True)
    organization_name=models.CharField(max_length=200, null=True)
    phone = PhoneNumberField()
    total_project = models.IntegerField(null=True,default=0,blank=True)
    location = models.CharField(max_length=255, null=True,blank=True)
    experiance = models.TextField(null=True,blank=True)
    profile_pic = models.ImageField(default="profile1.png", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)


    def __str__(self):
        return self.user.username

class CreateForm(models.Model):
    form_name = models.CharField(max_length=255,unique=True)
    form_code = models.TextField()
    created_at= models.DateTimeField(auto_now_add=True, null=True)
    updated_at= models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.form_name

class CreateProject(models.Model):
    project_name = models.CharField(max_length=255, unique=True)
    project_description = models.TextField()
    status_choices = [('pending','pending'),('assigned','assigned'),('completed','completed')] 
    status = models.CharField(max_length=15,choices=status_choices,default='pending')
    forms = models.ManyToManyField(CreateForm)
    estimated_budget = models.CharField(max_length=30,null=True)
    estimated_project_duration = models.CharField(max_length=15,null=True)
    apply_start_date = models.DateTimeField(null=True)
    apply_end_date = models.DateTimeField(null=True)
    assigned_by = models.CharField(max_length=255,null=True)
    assigned_to = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True)
    assigned_details = models.TextField(null=True)
    project_progress = models.IntegerField(null=True,default=0,blank=True)
    Complete_details = models.TextField(null=True)
    complete_Rating = models.DecimalField(max_digits=2, decimal_places=1,null=True)
    created_at= models.DateTimeField(auto_now_add=True, null=True)
    updated_at= models.DateTimeField(auto_now_add=True, null=True)

    @property
    def is_On_Time(self):
        return (timezone.now() > self.apply_start_date) and (timezone.now() < self.apply_end_date)

    def __str__(self):
        return self.project_name


class FormData(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    project = models.ForeignKey(CreateProject, on_delete=models.CASCADE)
    form_name= models.ForeignKey(CreateForm,on_delete=models.PROTECT)
    submited_data = models.JSONField(null=True, blank=True)
    submited_File = models.JSONField(null=True, blank=True)
    submited_at= models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        constraints = [models.UniqueConstraint(fields=['user','project','form_name'],name='user_project_formName')]

    def __str__(self):
        return str(self.user)+" "+str(self.project)+" "+str(self.form_name)

class applyProject(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    project = models.ForeignKey(CreateProject, on_delete=models.CASCADE)
    forms = models.ManyToManyField(FormData)
    date_applyed = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        constraints = [models.UniqueConstraint(fields=['user','project'],name='user_project_forms')]

    def __str__(self):
        return str(self.user)+" "+str(self.project)

class trackProject(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    project = models.ForeignKey(CreateProject, on_delete=models.CASCADE)
    track_status=models.CharField(max_length=255,null=True)
    track_description = models.TextField()
    project_progress = models.IntegerField(null=True,default=0,blank=True)
    created_at= models.DateTimeField(auto_now_add=True, null=True)
    updated_at= models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.track_status)+" "+str(self.project)+" "+str(self.user)


class pastProject(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    project_name = models.CharField(max_length=255)
    project_description = models.TextField()
    estimated_budget = models.CharField(max_length=30,null=True)
    estimated_project_duration = models.CharField(max_length=15,null=True)
    Complete_details = models.TextField(null=True)
    complete_Rating = models.DecimalField(max_digits=2, decimal_places=1,null=True)
    created_at= models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str(self.user) +" "+ str(self.project_name)

@receiver(post_save,sender=CustomUser)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        if instance.user_type==1:
            SuperUserProfile.objects.create(user=instance)
        if instance.user_type==2:
            GovermentUserProfile.objects.create(user=instance)
        if instance.user_type==3:
            OrganizationUserProfile.objects.create(user=instance)

@receiver(post_save,sender=CustomUser)
def save_user_profile(sender,instance,**kwargs):
    if instance.user_type==1:
        instance.superuserprofile.save()
    if instance.user_type==2:
        instance.govermentuserprofile.save()
    if instance.user_type==3:
        instance.organizationuserprofile.save()


@receiver(post_save,sender=pastProject)
def Update_user_profile_project(sender,instance,created,**kwargs):
    if created:
        print(instance)
        print(instance.user)
        profile = OrganizationUserProfile.objects.filter(user=instance.user).first()
        past_project_count = pastProject.objects.filter(user=instance.user).count()
        profile.total_project = past_project_count
        profile.save()
        print("project updated")

Deshboard/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import SuperUserProfile,GovermentUserProfile,OrganizationUserProfile,CustomUser,CreateProject,pastProject

User = get_user_model()

class CreateUserForm(UserCreationForm):

	class Meta:
		model = User
		fields  =['username', 'email', 'password1', 'password2','first_name','last_name']

class UpdateUserForm(ModelForm):

	class Meta:
		model = User
		fields  =['username', 'email','first_name','last_name']
	

class SuperUserProfileForm(ModelForm):
	class Meta:
		model = SuperUserProfile
		fields = '__all__'
		exclude =['user']


class GovermentUserProfileForm(ModelForm):
	class Meta:
		model = GovermentUserProfile
		fields = '__all__'
		exclude =['user']


class OrganizationUserProfileForm(ModelForm):
	class Meta:
		model = OrganizationUserProfile
		fields = '__all__'
		exclude =['user','total_project']

class CreateProjectForm(ModelForm):
	class Meta:
		model = CreateProject
		fields = '__all__'
		exclude =['assigned_by','assigned_to','assigned_details','Complete_details','complete_Rating']

class AddPastProjectsForm(ModelForm):
	class Meta:
		model = pastProject
		fields = '__all__'
		exclude=['user','Complete_details','complete_Rating']

Deshboard/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm


# Create your views here.

def userlogin(request):
    if request.user.is_authenticated:
        if request.user.user_type == '1':
            print(request.user.id)
            return redirect('SuHome')
        elif request.user.user_type == '2':
            return redirect('GoHome')
        elif request.user.user_type == '3':
            return redirect('OrHome')
    else:
        if request.method == 'POST':
            username =request.POST.get('username')
            password =request.POST.get('password')
            user = authenticate(request,username=username,password=password)

            if user is not None:
                login(request,user)
                if user.user_type == '1':
                    return redirect("SuHome")
                elif user.user_type == '2':
                    return redirect("GoHome")
                elif user.user_type == '3':
                    return redirect("OrHome")
            else:
                messages.info(request, 'Username OR Password is incorrect.')
        
    contex={}
    return render(request, 'Deshboard/login.html',contex)

@login_required(login_url='login')
def userlogout(request):
	logout(request)
	return redirect('login')

@login_required(login_url='login')
def ChangePassword(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
        user=''
    if request.user.user_type == '1':
        user='Deshboard/Superuser/superuser.html'
    elif request.user.user_type == '2':
        user='Deshboard/Governmentuser/government.html'
    elif request.user.user_type == '3':
        user='Deshboard/Organizationuser/organization.html'
    contex = {'form':form,"user":user}
    return render(request, 'Deshboard/change_password.html',contex)

Deshboard/templates/Deshboard/Superuser/ShowformList.html
{% extends user %}
{% load static %}

{% block projectopen %}
menu-open
{% endblock projectopen %}

{% block ShowFormActive %}
active
{% endblock ShowFormActive %}

{% block projectactive %}
active
{% endblock projectactive %}

{% block style %}
      <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'Deshboard/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'Deshboard/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'Deshboard/plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
{% endblock style %}

{% block script %}
  
<!-- DataTables  & Plugins -->
<script src="{% static 'Deshboard/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'Deshboard/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'Deshboard/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'Deshboard/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<!-- <script src="{% static 'Deshboard/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'Deshboard/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script> -->
<!-- <script src="{% static 'Deshboard/plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'Deshboard/plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'Deshboard/plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'Deshboard/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'Deshboard/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'Deshboard/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script> -->

<script>
    $(function () {
        $('#example2').DataTable({
      "paging": true,
      // "lengthChange": true,
      "searching": true,
      "ordering": true,
      "autoWidth": false,
      // "responsive": true,
      "scrollY": true,
      "scrollX": true,

    });
    });
  </script>

{% endblock script %}

{% block body %}
  
<div class="container-fluid">

    <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Form List</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example2" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th class="text-center" scope="col">#</th>
                            <th class="text-center" scope="col">Form Name</th>
                            <th class="text-center" scope="col"></th>
                          </tr>
                    </thead>
                    <tbody>
                        {% for name in formnames %}
                        <tr>
                          <th class="text-center" scope="row" class="text-center">{{forloop.counter}}</th>
                          <td class="text-center">{{name}}</td>
                          <td class="text-center"><a href="{% url 'ShowForm' name.id %}" target="_blank" class="btn btn-success btn-sm">show </a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <th class="text-center" scope="col">#</th>
                            <th class="text-center" scope="col">Form Name</th>
                            <th class="text-center" scope="col"></th>
                          </tr>
                    </tfoot>
                  </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>

</div>

{% endblock %}

Deshboard/templates/Deshboard/Superuser/createGovUser.html
{% extends "./superuser.html" %}

{% block GovUserActive %}
active
{% endblock %}

{% block createuseropen %}
menu-open
{% endblock createuseropen %}

{% block createuseractive %}
active
{% endblock createuseractive %}

{% block body %}
  
<div class="container-fluid">
{% include "../message.html" %}
    <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Goverment User</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form method="post" class="form-validate">{% csrf_token %}
          <div class="card-body">
            <div class="row">
              <div class="form-group col">
                <label for="id_first_name">First name</label>
                <input type="text" class="form-control" id="id_first_name" name="first_name" placeholder="First name" required>
              </div>
              <div class="form-group col">
                <label for="id_last_name">Last name</label>
                <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="Last name" required>
              </div>
            </div>
            <div class="row">
            <div class="form-group col">
                <label for="id_username">User name</label>
                <input type="text" class="form-control" id="id_username" name="username" placeholder="User name" autofocus required>
            </div>
            <div class="form-group col">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" id="id_email" name="email" placeholder="Enter email" required>
            </div>
          </div>
          <div class="row">
            <div class="form-group col">
                <label for="id_job_role">Job role</label>
                <input type="text" class="form-control" id="id_job_role" maxlength="200" name="job_role" placeholder="Job role" required>
            </div>
            <div class="form-group col">
                <label for="id_goverment_id">Goverment id</label>
                <input type="number" class="form-control" id="id_goverment_id" name="goverment_id" placeholder="Goverment id" required>
            </div>
          </div>
            <div class="form-group">
                <label>Contact number</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-phone"></i></span>
                  </div>
                  <input type="tel" id="id_phone" maxlength="15" name="phone" class="form-control" placeholder="+912545848596" required>
                </div>
              </div>
            <div class="form-group">
              <label for="id_password1">Password</label>
              <input type="password" class="form-control" id="id_password1" name="password1" placeholder="Password" required>
            </div>
            <div class="form-group">
              <label for="id_password2">Conform Password</label>
              <input type="password" class="form-control" id="id_password2" name="password2" placeholder="Conform Password" required>
            </div>
          </div>
          <!-- /.card-body -->

          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
          {% include "../error.html" %}
        </form>
      </div>
</div><!-- /.container-fluid -->

{% endblock body %}

Deshboard/templates/Deshboard/Superuser/createProject.html
{% extends "./superuser.html" %}
{% load static %}

{% block projectopen %}
menu-open
{% endblock projectopen %}

{% block CreateProjectActive %}
active
{% endblock CreateProjectActive %}

{% block projectactive %}
active
{% endblock projectactive %}

{% block style %}

  <!-- Select2 -->
  <link rel="stylesheet" href="{% static 'Deshboard/plugins/select2/css/select2.min.css' %}">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'Deshboard/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">

{% endblock style %}

{% block script %}

<!-- Select2 -->
<script src="{% static 'Deshboard/plugins/select2/js/select2.full.min.js' %}"></script>

<!-- moment.js -->
<script src="{% static 'Deshboard/plugins/moment/moment.min.js' %}"></script>

<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'Deshboard/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<script>
  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()
    $('#datetimepicker1').datetimepicker({
      icons: { time: "fa fa-clock", },
      format: 'MM/DD/YYYY HH:mm',
    });
        $('#datetimepicker2').datetimepicker({
          useCurrent: false,
          icons: { time: "fa fa-clock", },
          format: 'MM/DD/YYYY HH:mm',
        });
        $("#datetimepicker1").on("change.datetimepicker", function (e) {
            $('#datetimepicker2').datetimepicker('minDate', e.date);
        });
        $("#datetimepicker2").on("change.datetimepicker", function (e) {
            $('#datetimepicker1').datetimepicker('maxDate', e.date);
        });
  })
</script>

{% endblock script %}

{% block body %}
  
<div class="container-fluid">

  <section class="content">
    <form method="post" class="form-validate">{% csrf_token %}
      {% include "../message.html" %}
    <div class="row">
      <div class="col-md-6">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">General</h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
              </button>
            </div>
          </div>
          
          <div class="card-body">
            <div class="form-group">
              <label for="id_project_name">Project Name</label>
              <input type="text" name="project_name" id="id_project_name" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="id_project_description">Project Description</label>
              <textarea id="id_project_description" name="project_description" class="form-control" rows="4" required></textarea>
            </div>
            <div class="form-group">
              <label for="inputStatus">Status</label>
              <select id="id_status" name="status" class="form-control custom-select">
                <option selected disabled>Select one</option>
                <option value="pending" selected="">Pending</option>
                <option value="assigned">Assigned</option>
                <option value="completed">Completed</option>
              </select>
            </div>
              <div class="form-group">
                <label>Forms</label>
                <div class="select2-success">
                <select class="select2" name="forms" id="id_forms" required multiple="multiple" data-placeholder="Select a State" style="width: 100%;">
                  {% for i in all_form_name %}
                  <option value="{{i.id}}">{{i.form_name}}</option>
                  {% endfor %}
                </select>
              </div>
              </div>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <div class="col-md-6">
        <div class="card card-secondary">
          <div class="card-header">
            <h3 class="card-title">Budget</h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
              </button>
            </div>
          </div>
          <div class="card-body">
            <div class="form-group">
              <label for="inputEstimatedBudget">Estimated budget</label>
              <input type="text" name="estimated_budget" maxlength="30" id="id_estimated_budget" required class="form-control">
            </div>
            <div class="form-group">
              <label for="inputEstimatedDuration">Estimated project duration</label>
              <input type="text" name="estimated_project_duration" maxlength="15" id="id_estimated_project_duration" required class="form-control">
            </div>
              <div class="form-group">
                <label for="id_apply_start_date">Apply Start Date</label>
                 <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                      <input type="text" name="apply_start_date" required id="id_apply_start_date" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
                      <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                          <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                      </div>
                  </div>
              </div>
              <div class="form-group">
                <label for="id_apply_end_date">Apply End Date</label>
                 <div class="input-group date" id="datetimepicker2" data-target-input="nearest">
                      <input type="text" name="apply_end_date" id="id_apply_end_date" required class="form-control datetimepicker-input" data-target="#datetimepicker2"/>
                      <div class="input-group-append" data-target="#datetimepicker2" data-toggle="datetimepicker">
                          <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                      </div>
                  </div>
              </div>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
    {% include "../error.html/" %}
    <div class="row">
      <div class="col-7 mb-3">
        <input type="submit" value="Create new Porject" class="btn btn-success float-right">
      </div>
    </div>
  </form>
  </section>

</div>

{% endblock %}